<?php require VIEWS_PATH.'site/includes/header.phtml';?>

<div class="container text-justify">
    <h1>About</h1>

    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis ea numquam, 
        nostrum ducimus laboriosam optio quo vitae debitis culpa illum eius non, 
        sapiente est ex explicabo veniam, minus hic rem. Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Possimus pariatur vitae suscipit voluptatum modi facere nulla! 
        Voluptate tempore possimus quod officiis magni iste eligendi provident quibusdam, obcaecati, itaque, eius commodi!
    </p>

    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Vel voluptatem modi maxime eveniet aliquam provident deleniti officiis unde perspiciatis, 
        velit consequuntur natus et neque eaque laborum repellendus eligendi tenetur temporibus.
    </p>

    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis ea numquam, 
        nostrum ducimus laboriosam optio quo vitae debitis culpa illum eius non, 
        sapiente est ex explicabo veniam, minus hic rem. Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Possimus pariatur vitae suscipit voluptatum modi facere nulla! 
        Voluptate tempore possimus quod officiis magni iste eligendi provident quibusdam, obcaecati, itaque, eius commodi!
    </p>

</div>



<?php require VIEWS_PATH.'site/includes/footer.phtml';?>