<?php require VIEWS_PATH.'site/includes/header.phtml';?>

<div class="container">
    <h1>Contact us!</h1>

    <p>Fill the form below</p>

    <form>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Type your name">
        </div>
        <div class="form-group">
            <input type="email" class="form-control" placeholder="Type your e-mail" required>
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Type the subject">
        </div>
        <div class="form-group">
            <textarea name="message" class="form-control" id="" cols="30" rows="10" placeholder="Your message here!"></textarea>
        </div>
        <div class="pull-right">
            <input type="buttons" class="btn btn-primary" value="Send" >
        </div>
    </form>
</div>

<?php require VIEWS_PATH.'site/includes/footer.phtml';?>