<?php require VIEWS_PATH.'site/includes/header.phtml'; ?>

<div class="container">
    <h1>Project MVC with study purpose</h1>
    <p>
        To build this project was used the following technologies:
    </p>
    <p>
        <ul>
            <li>Bootstrap framework</li>
            <li>PHP version <?=phpversion();?></li>
            <li>Composer version 1.6.3</li>
        </ul>
    </p>
</div>

<?php require VIEWS_PATH.'site/includes/footer.phtml'; ?>